---

- name: Install tcpd package
  tags:
    - tcpd_install
    - tcpd
  become: true
  block:
    - name: Install tcpd package
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name: "{{ tcpd_package_name }}"
        update_cache: true
        state: "{{ tcpd_package_ensure }}"

    - name: Install tcpd package
      when: ansible_os_family == 'RedHat'
      ansible.builtin.yum:
        name: "{{ tcpd_package_name }}"
        state: "{{ tcpd_package_ensure }}"
